const express = require('express');
const router = express.Router();
const taskController = require('../controller/task.controller');
router.get('/', taskController.index);
router.get('/detail/:id', taskController.detail);
router.patch("/change-status/:id", taskController.changeStatus);
router.patch("/change-multi", taskController.changeMultiStatus);
router.post("/create", taskController.create);
router.delete("/delete/:id", taskController.delete);
router.patch("/edit/:id", taskController.edit);
module.exports = router;
